name: Build bundle
on:
  push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x

      - name: Recreate dist
        shell: bash
        run: rm -rf ./dist && mkdir -p ./dist

      - name: Formate
        shell: bash
        run: deno fmt --ignore=.github

      - name: Build bundle
        shell: bash
        run: deno run --allow-env --allow-read --allow-run --allow-write --allow-net bundle.ts

      - name: Commit and Push Changes
        continue-on-error: true
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add . # Добавить все изменения форматирования
          git commit -m "auto: build bundle file [skip ci]" # Создать НОВЫЙ коммит
          # [skip ci] в сообщении коммита часто используется, чтобы предотвратить запуск этого же workflow снова
          git push origin HEAD:${{ github.head_ref || github.ref_name }} # Пуш в ту же ветку, откуда пришел триггер